- app/list-picker.js
- app/style.css
- index.html
Merging most recent version back into the live version
> Layout update

- app/list-picker.js
- app/style.css
> Added feature to manually toggle items in the list

- app/list-picker.js
Pushing persistence layer for selected items live
> Save selected

- app/list-picker.js
Pushing new data structure live
> Item save update

- app/list-picker.js
- app/style.css
- index.html
Closes #9 
New feature to allow items in a list to be disabled and removed from the pool of available items to select. Items are retained in a separate list and can be reenabled to move them back into the selection pool.
> Disable items

- app/list-picker.js
- index.html
Pushing multiple list management live.
Closes #10
> Multiple lists

- .gitignore
- .travis.yml
- package.json
- webpack.config.js
> Updates to page build setup

- resources/html/index.html
- resources/js/lists/components/ListControls.js
> Disable button

- webpack.config.js
merging some corrections to webpack configuration paths
> Fix webpack path

- .travis.yml
- babel.config.js
- package-lock.json
- package.json
- resources/js/lists/components/CurrentItem.js
- resources/js/lists/components/ListControls.js
- resources/js/lists/components/ListImportExport.js
- resources/js/lists/controllers/ListItemPicker.js
- resources/js/lists/models/ListItem.js
- resources/js/lists/models/list.js
- resources/js/lists/models/lists.js
- resources/js/lists/store.js
- test/lists/models/List.test.js
- test/lists/models/ListItem.test.js
- test/lists/models/Lists.test.js
Merging first working unit tests to master
> Add model unit tests

- test/lists/models/List.test.js
The first test returns the only disabled item out of the two items on the List.
The second test returns an empty array if a List is empty.
> Tests whether the disabled computed property works

- resources/js/lists/models/List.js
- resources/js/lists/models/Lists.js
- resources/js/lists/store.js
- test/lists/models/List.test.js
- test/lists/models/Lists.test.js
Merging recently added unit tests.
Closes #39 
Closes #40 
Closes #41 
Closes #42
> List class unit tests

- test/lists/models/List.test.js
> Demo kanban automation

- resources/js/lists/models/List.js
- test/lists/models/List.test.js
> Is current test

- resources/js/lists/controllers/ListItemPicker.js
- resources/js/lists/index.js
- resources/js/lists/models/Lists.js
This bug was fixed before, but was reintroduced after some of the code reorganization.
> Fixing issue where the app is broken if you don't have a list already created

- resources/js/lists/components/ListControls.js
- resources/js/lists/components/ListModal.js
- resources/js/lists/controllers/ListItemPicker.js
- resources/js/lists/index.js
- resources/js/lists/models/List.js
- resources/js/lists/models/ListItem.js
- resources/js/lists/models/Lists.js
- resources/js/lists/store.js
- test/lists/models/List.test.js
- test/lists/models/ListItem.test.js
Merging in updates refactoring the save process to remove internal calls on other update functions. Was cause some issues with unintended saves happening so usage is now migrate to explicit calls in the component and controller classes.
> Refactor save process

- test/lists/models/List.test.js
> Created two tests for the currentIndex computed property

- t game = new Game();
- test/lists/models/Lists.test.js
> getIndex test built, truthy and null tests pass

- resources/js/lists/components/ListControls.js
> Updated Next button to restart the list

- resources/html/index.html
- resources/js/lists/components/ListControls.js
> Add previous button

- resources/js/lists/components/ListModal.js
- resources/js/lists/controllers/ListItemPicker.js
- resources/js/lists/models/Lists.js
If the modal is closed without clicking 'Save' button, then the new list is not saved and added to the collection of lists
Closes #28
> Add new list feature update:

- test/lists/models/List.test.js
Discovered some uncovered line of code in the List class by running npm test -- --collectCoverage.
> New List class unit tests

- resources/js/lists/controllers/ListItemPicker.js
- resources/js/lists/models/List.js
- resources/js/lists/models/Lists.js
- test/lists/models/Lists.test.js
Closes #59
Closes #61 
Closes #66
> Build lists class tests

- resources/js/lists/models/List.js
- test/lists/models/List.test.js
> Removed external usage of Lists.currentListKey

- package-lock.json
- package.json
> Removing old references to gh-pages deployment

- LICENSE
- README.md
> Updated README file and added an MIT license

- README.md
- app/config/validation/register.js
- app/controllers/auth.js
- app/controllers/room.js
- app/models/Classroom.js
- app/models/Token.js
- app/seed/reset.js
- client/package-lock.json
- client/package.json
- client/src/App.sass
- client/src/pages/Dashboard/utils/icons.js
- client/src/pages/Dashboard/views/Team/components/InviteModal.js
- client/src/pages/Dashboard/views/Team/components/PendingInvitesModal.js
- client/src/pages/Dashboard/views/Team/components/StaffListControls.js
- client/src/pages/Register/components/RegisterForm.js
- client/src/utils/auth.js
- package-lock.json
- package.json
- registercode.js
Merging in enrollment code features and email bypass updates.
> Enrollment codes

- app/config/io.js
- app/controllers/app.js
- app/controllers/invite.js
- app/controllers/room.js
- app/controllers/student.js
- app/controllers/user.js
- app/controllers/utils/ioEmit.js
- app/routes/middleware/isAuthenticated.js
- client/src/pages/Dashboard/components/ManageApps.js
- client/src/pages/Dashboard/components/StudentCard/index.js
- client/src/pages/Dashboard/components/StudentModal/components/ActivityFeed/components/CommentForm.js
- client/src/pages/Dashboard/components/StudentModal/components/ActivityFeed/index.js
- client/src/pages/Dashboard/components/StudentModal/components/SettingsForm.js
- client/src/pages/Dashboard/components/StudentModal/components/StudentOptions.js
- client/src/pages/Dashboard/components/StudentModal/index.js
- client/src/pages/Dashboard/components/Topbar/index.js
- client/src/pages/Dashboard/index.js
- client/src/pages/Dashboard/store/actions.js
- client/src/pages/Dashboard/store/actionsNames.js
- client/src/pages/Dashboard/store/index.js
- client/src/pages/Dashboard/store/loaders.js
- client/src/pages/Dashboard/utils/apps.js
- client/src/pages/Dashboard/utils/feed.js
- client/src/pages/Dashboard/views/Classroom/components/Widget/index.js
- client/src/pages/Dashboard/views/Classroom/index.js
- client/src/pages/Dashboard/views/Students/components/StudentListControls.js
- client/src/pages/Dashboard/views/Team/components/InviteModal.js
- client/src/pages/Dashboard/views/Team/components/Member.js
- client/src/pages/Dashboard/views/Team/components/PendingInvitesModal.js
- client/src/utils/socket.io.js
Merging in current code for socket.io rework. All previous features are working again and have been verified for secure messaging, so only the appropriate sockets receive targeted messages.
> Sockit.io rework

- app/config/io.js
- client/src/utils/auth.js
Sockets now correctly reauthenticate after a use logs in and unauthenticates when they log out.
> Fixed socket authentication inconsistencies

- client/src/pages/Dashboard/components/StudentModal/components/ActivityFeed/index.js
- client/src/pages/Dashboard/store/loaders.js
Added the Pulse loader icon while the feed is loading.
> Active feed is now cleared from the store when its closed.

- client/src/App.sass
- client/src/pages/Dashboard/components/StudentModal/components/ActivityFeed/index.js
- client/src/pages/Dashboard/components/StudentModal/index.js
Fixed some display issues with larger scrolling feeds that cause issues with the modal as a whole. Also built in an auto scroll to bottom feature.
> Fixed feed scrolling so it stays self contained.

- app/config/express.js
- app/config/io.js
- app/config/jwtstrategy.js
- app/config/mongoose.js
- app/config/options.js
- app/config/utils/mail.js
- app/controllers/auth.js
- app/controllers/invite.js
- app/controllers/utils/sendUserVerifyEmail.js
- client/src/pages/Dashboard/views/Team/components/PendingInvitesModal.js
- client/src/utils/socket.io.js
- Replaces all hardcoded usages of localhost:3000 with dynamic/configurable values.
- Created a new readonly options solution for organizing server side configuration.
> Fix localhost urls

- app/config/options.js
- app/config/utils/mail/index.js
- app/config/utils/mail/strategies/SendGridStrategy.js
- app/config/utils/mail/strategies/SmtpStrategy.js
- app/config/utils/mail/strategies/Strategy.js
- client/src/pages/Dashboard/views/Team/components/PendingInvitesModal.js
- package-lock.json
- package.json
- Added new SMTP options to app config.
- Refactored email solution into selectable strategies to allow different plug and play solutions.
- Added nodemailer for SMTP emails and built it into an SmtpStrategy for integration.
>  Email Strategy Refactor

- app/controllers/feed/entries/types/CommentEntryType.js
- app/models/methods/student.js
- client/src/components/UserName.js
- client/src/pages/Dashboard/views/Team/components/Member.js
- client/src/pages/Developers/components/LeadDev.js
**Included Updates**
- Added aggregate update for `recentComments` with a comment is added.
> Recent comment update

- client/package-lock.json
- client/package.json
- client/src/components/Date.js
**Included Updates**
- Added new package to client `luxon` for handling date/time formatting.
- Implemented Luxon in the Date component used on all comments to format relative dates by default.
> Readable dates

- app/config/errors/RouteError.js
- app/config/express.js
- app/config/io.js
- app/config/options.js
- app/controllers/app.js
- app/controllers/auth.js
- app/controllers/emailValidation.js
- app/controllers/feed/entries/types/CommentEntryType.js
- app/controllers/feed/entries/types/ElevationEntryType.js
- app/controllers/feed/entries/types/EntryType.js
- app/controllers/feed/index.js
- app/controllers/invite.js
- app/controllers/register.js
- app/controllers/room.js
- app/controllers/student.js
- app/controllers/user.js
- app/controllers/utils/ioEmit.js
- app/routes/_auth.js
- app/routes/invites.js
- app/routes/isAuth/apps.js
- app/routes/isAuth/feeds.js
- app/routes/isAuth/rooms.js
- app/routes/isAuth/students.js
- app/routes/isAuth/user.js
- app/routes/middleware/createControllerHandler.js
- app/routes/middleware/setDefaultError.js
- app/routes/register.js
- app/routes/validate.js
- app/server.js
**Included Updates**
- Major refactor of route error handling. All route errors now pass through a central error handler for unified approach to handling and responding to those errors.
- Major refactor of how routes and controllers are organized.
**Route/Controller Changes**
- All controller methods are now decoupled from direct interaction with the `req` or `res` objects from express routes. Instead, all that logic is abstracted into a common "controller handler" method which can be created and configured using the `createControllerHandler` method.
- Controllers now accept a new custom aggregate objects that contains all `route.params` as direct properties, the `user` object if available, the request `body`, and then any custom included `req` properties declared in the config passed to …
> Route ctrl remodel

- app/server.js
- package-lock.json
- package.json
Had a bad package-lock.json file
> Unit testing

- app/config/permissions/sets/FeedDelevateSet.js
- Fixed issue with deelevate permission not working correctly
> Permission fix

- app/controllers/invite.js
- client/src/pages/Dashboard/views/Team/components/PendingInvitesModal.js
Fixed old usage of missing Room model and fixed the PendingInvitesModal to use the new 'tokenString' property.
> Fix TA Invite with no email system

- package-lock.json
- package.json
Hot fix for module aliases failing in unit tests
> Fix module aliases

- seed/data/classrooms.js
- seed/seeds/seedClassroom.js
- seed/seeds/seedUser.js
> updated seed location

- client/src/components/Routes.js
- Added ability for `PrivateRoute` and `GuestRoute` components to accept the same `component` property as `Route`
- Other minor syntax updates for cleaner code
> Routes Update

- seed/data/classrooms.js
Including an update to the demo seed to match updates from the aggregate refactor.
> Updated seed to include student schema updates.

- app/config/io.js
- client/src/pages/Dashboard/store/loaders.js
- client/src/pages/Dashboard/utils/feed.js
- Updated io controller to allow multiple actions per channel key
- Updated useHandleFeedEventResponse to emit dynamic actions
- Updated useStudentFeedLoader to handle update and delete message actions
> Created update and delete socket messaging for feeds

- registercode.js
> fix models import.

- app/config/io.js
- client/src/pages/Dashboard/store/loaders.js
- client/src/pages/Dashboard/utils/feed.js
- package.json
- registercode.js
Version update 0.5.10 -> 0.5.11
**Included updates**
- Created update and delete socket messaging for feeds items @ac524
- Fixed bug with the script for generating new registration codes @ac524
> Weekly Build 3-30-2021

- app/controllers/definitions/FeedEntryController.js
- app/controllers/types/Controller.js
- app/controllers/types/SchemaController.js
- app/controllers/types/SubSchemaController.js
The base controller classes have been extended to save into a centralized library that each can access to call upon other controller to create external side effects.
> Controller effects feature

- app/routes/validation/definitions/appValidation.js
- client/src/pages/Dashboard/components/ManageApps.js
- Updated app validation schema to look for the correct `room` property instead of `roomId`.
- Updated manage apps to correctly update state after installing an app.
> Fix app install

- app/controllers/definitions/ValidateEmailController.js
Removed imports for token and user controllers and updated usages to access them through the 'effect' function
> Fix Ctrl Interaction

- app/config/apps/register.js
- app/config/io.js
- app/controllers/app.js
- app/controllers/appType.js
- app/controllers/auth.js
- app/controllers/feed.js
- app/controllers/feedentries.js
- app/controllers/index.js
- app/controllers/invite.js
- app/controllers/register.js
- app/controllers/room.js
- app/controllers/student.js
- app/controllers/token.js
- app/controllers/user.js
- app/controllers/utils/searchCtrls.js
- app/controllers/validateEmail.js
- app/routes/_auth.js
- app/routes/apps.js
- app/routes/feeds.js
- app/routes/invites.js
- app/routes/middleware/setFeed.js
- app/routes/middleware/setInvite.js
- app/routes/middleware/setRoom.js
- app/routes/register.js
- app/routes/rooms.js
- app/routes/students.js
- app/routes/user.js
- app/routes/validateEmail.js
From @Tuzosdaniel12 
- Refactor files of creating controllers instance into single file.
- Updated routes files to require controllers from index file in Controllers folder.
- Changed they way io.js access roomCtrl by using library.js
From @ac524 
**Addressed inconsistency with feed entry ctrl exports.**
- Created new searchCtrls utility function to search for ctrls by partial path matches
- Refactored routes/feeds to use new utility function instead of the nested object collection of ctrls.
> Refactor intance files single file

- client/src/service-worker.js
**ClickUp:** https://sharing.clickup.com/t/h/tx92vc/ATN4EX7O6TPPYN1
- changed cache-api-routes to only catch route that start with api by using group reg ex
- change cache-routes to catch every route not specified, added plugins to ignore socket.io routes
> modified:   client/src/service-worker.js

- .travis.yml
- app/routes/validation/definitions/commentValidation.js
- client/package-lock.json
- client/package.json
- client/src/components/Form/components/FormField.js
- client/src/components/Form/components/FormInput.js
- client/src/components/Form/components/RichTextEditor/index.js
- client/src/components/Form/components/RichTextEditor/styles.sass
- client/src/components/Form/index.js
- client/src/pages/Dashboard/components/StudentModal/components/ActivityFeed/components/CommentForm.js
- client/src/pages/Dashboard/components/StudentModal/components/ActivityFeed/entries/Comment.js
- client/src/pages/Dashboard/components/StudentModal/components/ActivityFeed/style.sass
- client/src/pages/Dashboard/components/StudentModal/index.js
- client/src/pages/Dashboard/components/StudentModal/index.sass
- client/src/pages/Dashboard/components/StudentModal/utils.js
- client/src/pages/Dashboard/views/Team/components/Member.js
- client/src/service-worker.js
- package-lock.json
- package.json
Version update 0.6.1 -> 0.6.2
**Sprint Board:** https://sharing.clickup.com/b/h/6-73575743-2/2ed6350e3c4b73f
**Included updates**
- **Enhancement:** - Improved student modal functionality and styles on modal @Tuzosdaniel12 #242
- **Enhancement:** - Made the feed comment box hidden by default, shown with a "click to comment" button @Tuzosdaniel12 #242
- **Feature:** - Added a new "RichText" field that uses DraftJS to create formatted content. Updated all code surrounding comment content to expect and handle to rich text content. @JJHPhoto @ac524 #243
- **Cleanup:** - Removed socket.io request pwa cache @Tuzosdaniel12 #244 #246
**New Client Packages** #243 
- draft-js@0.11.7
- @draft-js-plugins/editor@4.1.0
- @draft-js-plugins/static-toolbar@4.1.0
> 2021 Build 7 - 4-27-2021

- client/src/pages/Dashboard/components/StudentModal/index.sass
- client/src/pages/Dashboard/components/StudentModal/panels/StudentPanel.js
**ClickUp:** https://sharing.clickup.com/t/h/vte8r0/XG30QWFRRO1FTM7
Updated sass file to remove the padding of column when tabs are active
modified:   client/src/pages/Dashboard/components/StudentModal/panels/StudentPanel.js
flip the logic to have rounded corners on the modal
> modified:   client/src/pages/Dashboard/components/StudentModal/index.sass

- client/src/components/Login.js
- client/src/components/Modal/utils.js
On This Pull fix few imports at Login.js and utils.js
-  imported ```Box, Heading``` Components and ```useModalRegistration``` hook to ```Login```
- removed imports ```Box, Heading, LoginForm``` Components from Modal utils
> Fix Imports of Login.js and utils.js 

- client/src/pages/Dashboard/views/Students/components/StudentListControls.js
**ClickUp:** https://sharing.clickup.com/t/h/w3c2u0/8LGUKRC7NEUVD81
Added a `Clear` button that unselects students by using the `UNSELECT_ALL_STUDENTS` action.
> "clear selected" button

- client/src/pages/Dashboard/views/Team/components/PendingInvitesModal.js
- client/src/pages/Dashboard/views/Team/components/StaffListControls.js
On this pull:
- Updated PendingInvitesModal.js and StaffListControls.js
- Creaded usePendingInvitesModal() to register modal when needed on StaffListControls.js
- Removed Bulma Modal Components
- Moved content of PendingInvitesModal  to PendingInvitesModalContent
- Removed all unused code in both PendingInvitesModal.js and StaffListControls.js
> Adapt Pending Modal

- app/config/graphql_schemas/resolvers.js
- app/config/graphql_schemas/typeDefs.js
Created a login mutation in the graphQL typeDefs and resolvers files.
> Login mutation

- app/config/express.js
- app/config/graphql_schemas/resolvers.js
- app/config/graphql_schemas/typeDefs.js
**Click Up:**
https://sharing.clickup.com/t/h/1pt78qr/PDT49LQ50R6WY40
https://sharing.clickup.com/t/h/1pt78vq/0WMYUX72LA2OHRO
Added a context function to the apollo server and added a graphql version of the authenticated route.
> Jp graphql authenticated
